/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.udea.zooapp.view;

import edu.udea.zooapp.controller.LogisticController;
import edu.udea.zooapp.model.DomesticAnimal;
import javax.swing.JOptionPane;

/**
 *
 * @author xaraxx
 */
public class CreateDomesticAnimal extends javax.swing.JPanel {
    LogisticController logistic;

    /**
     * Creates new form CreateDomesticAnimal
     */
    public CreateDomesticAnimal() {
        initComponents();
        this.logistic = logistic;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stateDAJLabel = new javax.swing.JLabel();
        jTextFieldOriginDA = new javax.swing.JTextField();
        lableGenderDA = new javax.swing.JLabel();
        jLabelOrginDA = new javax.swing.JLabel();
        labelWeightDA = new javax.swing.JLabel();
        inputWeightDA = new javax.swing.JTextField();
        jSpinnerAgeDA = new javax.swing.JSpinner();
        jLabelPsycologyDA = new javax.swing.JLabel();
        labelNameDA = new javax.swing.JLabel();
        maleOptDA = new javax.swing.JRadioButton();
        jTextFieldPsycologyDA = new javax.swing.JTextField();
        inputNameDA = new javax.swing.JTextField();
        femaleOptDA = new javax.swing.JRadioButton();
        labelAgeDA = new javax.swing.JLabel();
        stateDAJComboBox = new javax.swing.JComboBox<>();
        jScrollPanePedigreeDA = new javax.swing.JScrollPane();
        jTextPanePedigree = new javax.swing.JTextPane();
        jLabelScientNameDA = new javax.swing.JLabel();
        inputScientifNameDA = new javax.swing.JTextField();
        pedigreeDAJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        createDAJButton = new javax.swing.JButton();

        stateDAJLabel.setText("Estado ");

        lableGenderDA.setText("Género");

        jLabelOrginDA.setText("Orígen");

        labelWeightDA.setText("Peso");

        jLabelPsycologyDA.setText("Sicología");

        labelNameDA.setText("Nombre");

        maleOptDA.setText("Macho");

        femaleOptDA.setText("Hembra");

        labelAgeDA.setText("Edad");

        stateDAJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Embarazo", "Enfermedad", "Discapacidad", "Saludable", "Óptimo", " " }));
        stateDAJComboBox.setPreferredSize(new java.awt.Dimension(64, 24));

        jTextPanePedigree.setPreferredSize(new java.awt.Dimension(64, 24));
        jScrollPanePedigreeDA.setViewportView(jTextPanePedigree);

        jLabelScientNameDA.setText("Nombre Científico. ");

        inputScientifNameDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputScientifNameDAActionPerformed(evt);
            }
        });

        pedigreeDAJLabel.setText("Pedigree");

        jLabel1.setText("Producto");

        jScrollPane1.setViewportView(jTextPane1);

        createDAJButton.setText("Crear");
        createDAJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDAJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPsycologyDA)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPsycologyDA, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(createDAJButton)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelOrginDA)
                            .addGap(190, 190, 190)
                            .addComponent(jTextFieldOriginDA))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pedigreeDAJLabel)
                            .addGap(176, 176, 176)
                            .addComponent(jScrollPanePedigreeDA))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelAgeDA)
                                .addComponent(labelNameDA)
                                .addComponent(jLabelScientNameDA))
                            .addGap(110, 110, 110)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inputScientifNameDA)
                                .addComponent(inputNameDA)
                                .addComponent(jSpinnerAgeDA)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lableGenderDA)
                                .addComponent(labelWeightDA))
                            .addGap(186, 186, 186)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inputWeightDA)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(maleOptDA)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                                    .addComponent(femaleOptDA))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(stateDAJLabel)
                            .addGap(184, 184, 184)
                            .addComponent(stateDAJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(302, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPsycologyDA)
                    .addComponent(jTextFieldPsycologyDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createDAJButton)
                .addGap(12, 12, 12))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(labelNameDA))
                        .addComponent(inputNameDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(labelAgeDA))
                        .addComponent(jSpinnerAgeDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelScientNameDA)
                        .addComponent(inputScientifNameDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(12, 12, 12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelWeightDA)
                        .addComponent(inputWeightDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(lableGenderDA))
                        .addComponent(maleOptDA)
                        .addComponent(femaleOptDA))
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(stateDAJLabel))
                        .addComponent(stateDAJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pedigreeDAJLabel)
                        .addComponent(jScrollPanePedigreeDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelOrginDA)
                        .addComponent(jTextFieldOriginDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(114, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputScientifNameDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputScientifNameDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputScientifNameDAActionPerformed

    private void createDAJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDAJButtonActionPerformed
        DomesticAnimal domesticAnimal = new DomesticAnimal();
        domesticAnimal.setName(inputNameDA.getText());
        domesticAnimal.setScientificName(inputScientifNameDA.getText());
        domesticAnimal.setWeight(Float.parseFloat(inputWeightDA.getText()));
        domesticAnimal.setAge(Float.parseFloat(jSpinnerAgeDA.getValue().toString()));
        domesticAnimal.setState(stateDAJComboBox.getSelectedItem().toString());
        domesticAnimal.setPedigree(jTextPanePedigree.getText());
        domesticAnimal.setPsycology(jTextFieldPsycologyDA.getText());
        domesticAnimal.setOrigin(jTextFieldOriginDA.getText());
        domesticAnimal.setGender(getGender());
        logistic.createDomesticAnimal(domesticAnimal);
    }//GEN-LAST:event_createDAJButtonActionPerformed

private String getGender() {
        if(maleOptDA.isSelected()) {
            return "Male";
        } else if (femaleOptDA.isSelected()) {
            return "Female";
        } else {
            JOptionPane.showMessageDialog(this, "Por favor selecciona un genero");
            throw new IllegalArgumentException("Gender is not valid, choose one");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createDAJButton;
    private javax.swing.JRadioButton femaleOptDA;
    private javax.swing.JTextField inputNameDA;
    private javax.swing.JTextField inputScientifNameDA;
    private javax.swing.JTextField inputWeightDA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelOrginDA;
    private javax.swing.JLabel jLabelPsycologyDA;
    private javax.swing.JLabel jLabelScientNameDA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPanePedigreeDA;
    private javax.swing.JSpinner jSpinnerAgeDA;
    private javax.swing.JTextField jTextFieldOriginDA;
    private javax.swing.JTextField jTextFieldPsycologyDA;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPanePedigree;
    private javax.swing.JLabel labelAgeDA;
    private javax.swing.JLabel labelNameDA;
    private javax.swing.JLabel labelWeightDA;
    private javax.swing.JLabel lableGenderDA;
    private javax.swing.JRadioButton maleOptDA;
    private javax.swing.JLabel pedigreeDAJLabel;
    private javax.swing.JComboBox<String> stateDAJComboBox;
    private javax.swing.JLabel stateDAJLabel;
    // End of variables declaration//GEN-END:variables
}
