/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.udea.zooapp.view;

import edu.udea.zooapp.controller.LogisticController;

/**
 *
 * @author xaraxx
 */
public class MainJFrameView extends javax.swing.JFrame {

    LogisticController logisticController;
    /**
     * Creates new form LogisticView
     * @param logistic
     */
    public MainJFrameView(LogisticController logistic) {
        initComponents();
        this.logisticController = logistic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        mainJMenuBar = new javax.swing.JMenuBar();
        animalsJMenu = new javax.swing.JMenu();
        jMenuItemCreateWA = new javax.swing.JMenuItem();
        jMenuItemReadWA = new javax.swing.JMenuItem();
        jMenuItemCreateDA = new javax.swing.JMenuItem();
        jMenuItemReadDA = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        animalsJMenu.setText("Gestión de Animales");

        jMenuItemCreateWA.setText("Crear Animal Salvaje");
        jMenuItemCreateWA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreateWAActionPerformed(evt);
            }
        });
        animalsJMenu.add(jMenuItemCreateWA);

        jMenuItemReadWA.setText("Consultar Animales Salvajes");
        jMenuItemReadWA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReadWAActionPerformed(evt);
            }
        });
        animalsJMenu.add(jMenuItemReadWA);

        jMenuItemCreateDA.setText("Crear Animal Doméstico");
        jMenuItemCreateDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreateDAActionPerformed(evt);
            }
        });
        animalsJMenu.add(jMenuItemCreateDA);

        jMenuItemReadDA.setText("Consultar Animales Domésticos");
        animalsJMenu.add(jMenuItemReadDA);

        mainJMenuBar.add(animalsJMenu);

        jMenu5.setText("Boletería");

        jMenuItem5.setText("Vender Boleta");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuItem6.setText("Consultar Ventas");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem7.setText("Generar Informe");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        mainJMenuBar.add(jMenu5);

        jMenu6.setText("Planes");

        jMenuItem8.setText("Añadir Plan");
        jMenu6.add(jMenuItem8);

        jMenuItem9.setText("Consultar Planes");
        jMenu6.add(jMenuItem9);

        jMenu7.setText("Generar Informe de Planes");
        jMenu6.add(jMenu7);

        mainJMenuBar.add(jMenu6);

        setJMenuBar(mainJMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 302, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCreateWAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreateWAActionPerformed
        jScrollPane1.setViewportView(new CreateWildAnimalPanel(logisticController));

    }//GEN-LAST:event_jMenuItemCreateWAActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    jScrollPane1.setViewportView(new CreatePlanPanel());    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItemCreateDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreateDAActionPerformed
        jScrollPane1.setViewportView(new CreateDomesticAnimal());
    }//GEN-LAST:event_jMenuItemCreateDAActionPerformed

    private void jMenuItemReadWAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReadWAActionPerformed
        logisticController.loadWildAnimals();
        jScrollPane1.setViewportView(new ListAnimalsPanel(logisticController.getWildAnimals()));
    }//GEN-LAST:event_jMenuItemReadWAActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu animalsJMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemCreateDA;
    private javax.swing.JMenuItem jMenuItemCreateWA;
    private javax.swing.JMenuItem jMenuItemReadDA;
    private javax.swing.JMenuItem jMenuItemReadWA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar mainJMenuBar;
    // End of variables declaration//GEN-END:variables
}
